require('dotenv').config();
const express=require('express'),cors=require('cors'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),{Pool}=require('pg');
const app=express(); app.use(cors({ origin: process.env.CORS_ORIGIN || true })); app.use(express.json({limit:'1mb'}));
const pool=new Pool({connectionString:process.env.DATABASE_URL});
const tok=u=>jwt.sign({id:u.id},process.env.JWT_SECRET,{expiresIn:'7d'});
function auth(req,res,next){try{const h=req.headers.authorization||''; if(!h.startsWith('Bearer '))throw 0; req.user=jwt.verify(h.slice(7),process.env.JWT_SECRET); next()}catch{res.status(401).json({error:'Session invalide'})}}
async function init(){await pool.query(`
CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,username VARCHAR(30) UNIQUE NOT NULL,email VARCHAR(255) UNIQUE NOT NULL,password_hash TEXT NOT NULL,native_language VARCHAR(20) NOT NULL,daily_goal INTEGER NOT NULL DEFAULT 10,xp INTEGER NOT NULL DEFAULT 0,streak INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS user_languages(id SERIAL PRIMARY KEY,user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,language_code VARCHAR(20) NOT NULL,level VARCHAR(2) DEFAULT 'A1',progress INTEGER DEFAULT 0,is_active BOOLEAN DEFAULT TRUE,UNIQUE(user_id,language_code));
CREATE TABLE IF NOT EXISTS friendships(id SERIAL PRIMARY KEY,requester_id INTEGER REFERENCES users(id) ON DELETE CASCADE,receiver_id INTEGER REFERENCES users(id) ON DELETE CASCADE,status VARCHAR(12) DEFAULT 'pending',created_at TIMESTAMPTZ DEFAULT NOW(),UNIQUE(requester_id,receiver_id));
CREATE TABLE IF NOT EXISTS blocks(id SERIAL PRIMARY KEY,blocker_id INTEGER REFERENCES users(id) ON DELETE CASCADE,blocked_id INTEGER REFERENCES users(id) ON DELETE CASCADE,UNIQUE(blocker_id,blocked_id));
CREATE TABLE IF NOT EXISTS conversations(id SERIAL PRIMARY KEY,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS conversation_members(conversation_id INTEGER REFERENCES conversations(id) ON DELETE CASCADE,user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,PRIMARY KEY(conversation_id,user_id));
CREATE TABLE IF NOT EXISTS messages(id SERIAL PRIMARY KEY,conversation_id INTEGER REFERENCES conversations(id) ON DELETE CASCADE,sender_id INTEGER REFERENCES users(id) ON DELETE CASCADE,content TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS notifications(id SERIAL PRIMARY KEY,user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,type VARCHAR(40) NOT NULL,title TEXT NOT NULL,body TEXT,read_at TIMESTAMPTZ,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS lessons(id SERIAL PRIMARY KEY,language_code VARCHAR(20) NOT NULL,title TEXT NOT NULL,description TEXT,level VARCHAR(2) DEFAULT 'A1',xp INTEGER DEFAULT 10,position INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS user_lesson_progress(user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,lesson_id INTEGER REFERENCES lessons(id) ON DELETE CASCADE,score INTEGER DEFAULT 0,completed BOOLEAN DEFAULT FALSE,completed_at TIMESTAMPTZ,PRIMARY KEY(user_id,lesson_id));
CREATE TABLE IF NOT EXISTS reports(id SERIAL PRIMARY KEY,reporter_id INTEGER REFERENCES users(id) ON DELETE CASCADE,reported_user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,reason VARCHAR(80) NOT NULL,details TEXT,created_at TIMESTAMPTZ DEFAULT NOW());
ALTER TABLE users ADD COLUMN IF NOT EXISTS xp INTEGER NOT NULL DEFAULT 0; ALTER TABLE users ADD COLUMN IF NOT EXISTS streak INTEGER NOT NULL DEFAULT 0;
INSERT INTO lessons(language_code,title,description,level,xp,position) SELECT * FROM (VALUES
('en','Se présenter','Dire bonjour, son nom et son pays.','A1',10,1),('en','Conversations simples','Questions et réponses du quotidien.','A1',15,2),('en','Comprendre une phrase','Repérer les mots importants.','A1',15,3),
('es','Saludos','Les salutations essentielles.','A1',10,1),('de','Erste Wörter','Premiers mots en allemand.','A1',10,1),('it','Presentarsi','Se présenter en italien.','A1',10,1)) x(language_code,title,description,level,xp,position) WHERE NOT EXISTS(SELECT 1 FROM lessons l WHERE l.language_code=x.language_code AND l.position=x.position);`)}
app.get('/api/health',async(_,r)=>{try{await pool.query('SELECT 1');r.json({ok:true})}catch{r.status(503).json({ok:false})}});
app.post('/api/auth/register',async(req,res)=>{const{username,email,password,nativeLanguage,dailyGoal=10,languages=[]}=req.body;if(!username||!email||!password||!nativeLanguage)return res.status(400).json({error:'Champs obligatoires manquants'});if(password.length<8)return res.status(400).json({error:'Mot de passe : 8 caractères minimum'});if(!Array.isArray(languages)||languages.length>4)return res.status(400).json({error:'Maximum 4 langues'});const c=await pool.connect();try{await c.query('BEGIN');const h=await bcrypt.hash(password,12);const q=await c.query('INSERT INTO users(username,email,password_hash,native_language,daily_goal) VALUES($1,$2,$3,$4,$5) RETURNING id,username,email,native_language,daily_goal,xp,streak',[username.trim(),email.trim().toLowerCase(),h,nativeLanguage,Number(dailyGoal)]);const u=q.rows[0];for(const l of languages)await c.query('INSERT INTO user_languages(user_id,language_code,level) VALUES($1,$2,$3)',[u.id,l.code,l.level||'A1']);await c.query('COMMIT');res.status(201).json({token:tok(u),user:u})}catch(e){await c.query('ROLLBACK');res.status(e.code==='23505'?409:500).json({error:e.code==='23505'?'Nom d’utilisateur ou email déjà utilisé':'Erreur serveur'})}finally{c.release()}});
app.post('/api/auth/login',async(req,res)=>{const{email,password}=req.body;const q=await pool.query('SELECT * FROM users WHERE email=$1',[(email||'').trim().toLowerCase()]);if(!q.rowCount||!(await bcrypt.compare(password||'',q.rows[0].password_hash)))return res.status(401).json({error:'Email ou mot de passe incorrect'});const u=q.rows[0];delete u.password_hash;res.json({token:tok(u),user:u})});
app.get('/api/me',auth,async(req,res)=>{const u=await pool.query('SELECT id,username,email,native_language,daily_goal,xp,streak,created_at FROM users WHERE id=$1',[req.user.id]);const l=await pool.query('SELECT language_code,level,progress,is_active FROM user_languages WHERE user_id=$1 ORDER BY id',[req.user.id]);if(!u.rowCount)return res.status(404).json({error:'Utilisateur introuvable'});res.json({user:u.rows[0],languages:l.rows})});
app.put('/api/me/onboarding',auth,async(req,res)=>{const{nativeLanguage,dailyGoal,languages}=req.body;if(!nativeLanguage||!Array.isArray(languages)||languages.length>4)return res.status(400).json({error:'Données invalides'});const c=await pool.connect();try{await c.query('BEGIN');await c.query('UPDATE users SET native_language=$1,daily_goal=$2 WHERE id=$3',[nativeLanguage,Number(dailyGoal||10),req.user.id]);await c.query('UPDATE user_languages SET is_active=FALSE WHERE user_id=$1',[req.user.id]);for(const l of languages)await c.query('INSERT INTO user_languages(user_id,language_code,level,is_active) VALUES($1,$2,$3,TRUE) ON CONFLICT(user_id,language_code) DO UPDATE SET level=EXCLUDED.level,is_active=TRUE',[req.user.id,l.code,l.level||'A1']);await c.query('COMMIT');res.json({ok:true})}catch{await c.query('ROLLBACK');res.status(500).json({error:'Sauvegarde impossible'})}finally{c.release()}});
app.get('/api/lessons',auth,async(req,res)=>{const code=(req.query.language||'en').slice(0,20);const r=await pool.query(`SELECT l.*,COALESCE(p.score,0) score,COALESCE(p.completed,false) completed FROM lessons l LEFT JOIN user_lesson_progress p ON p.lesson_id=l.id AND p.user_id=$1 WHERE l.language_code=$2 ORDER BY l.position`,[req.user.id,code]);res.json(r.rows)});
app.post('/api/lessons/:id/complete',auth,async(req,res)=>{const id=Number(req.params.id),score=Math.max(0,Math.min(100,Number(req.body.score||0)));const q=await pool.query('SELECT xp,language_code FROM lessons WHERE id=$1',[id]);if(!q.rowCount)return res.status(404).json({error:'Leçon introuvable'});const old=await pool.query('SELECT completed FROM user_lesson_progress WHERE user_id=$1 AND lesson_id=$2',[req.user.id,id]);let gain=old.rowCount&&old.rows[0].completed?0:q.rows[0].xp;await pool.query(`INSERT INTO user_lesson_progress(user_id,lesson_id,score,completed,completed_at) VALUES($1,$2,$3,true,NOW()) ON CONFLICT(user_id,lesson_id) DO UPDATE SET score=GREATEST(user_lesson_progress.score,EXCLUDED.score),completed=true,completed_at=NOW()`,[req.user.id,id,score]);await pool.query('UPDATE users SET xp=xp+$1,streak=GREATEST(streak,1) WHERE id=$2',[gain,req.user.id]);await pool.query('UPDATE user_languages SET progress=LEAST(100,progress+$1) WHERE user_id=$2 AND language_code=$3',[Math.max(1,Math.round(score/20)),req.user.id,q.rows[0].language_code]);res.json({ok:true,xpGained:gain})});
app.get('/api/users/search',auth,async(req,res)=>{const q=(req.query.q||'').trim();if(q.length<2)return res.json([]);const r=await pool.query('SELECT id,username,native_language FROM users WHERE id<>$1 AND username ILIKE $2 AND NOT EXISTS(SELECT 1 FROM blocks b WHERE b.blocker_id=$1 AND b.blocked_id=users.id) ORDER BY username LIMIT 20',[req.user.id,'%'+q+'%']);res.json(r.rows)});
app.post('/api/friends/request',auth,async(req,res)=>{const id=Number(req.body.receiverId);if(!id||id===req.user.id)return res.status(400).json({error:'Demande invalide'});const b=await pool.query('SELECT 1 FROM blocks WHERE (blocker_id=$1 AND blocked_id=$2) OR (blocker_id=$2 AND blocked_id=$1)',[req.user.id,id]);if(b.rowCount)return res.status(403).json({error:'Action impossible'});const r=await pool.query('INSERT INTO friendships(requester_id,receiver_id,status) VALUES($1,$2,\'pending\') ON CONFLICT(requester_id,receiver_id) DO NOTHING RETURNING *',[req.user.id,id]);if(!r.rowCount)return res.status(409).json({error:'Demande déjà envoyée'});await pool.query('INSERT INTO notifications(user_id,type,title,body) VALUES($1,\'friend_request\',\'Nouvelle demande d’ami\',$2)',[id,'Tu as reçu une demande d’ami.']);res.status(201).json(r.rows[0])});
app.get('/api/friends',auth,async(req,res)=>{const r=await pool.query('SELECT f.id,u.id user_id,u.username,u.native_language FROM friendships f JOIN users u ON u.id=CASE WHEN f.requester_id=$1 THEN f.receiver_id ELSE f.requester_id END WHERE (f.requester_id=$1 OR f.receiver_id=$1) AND f.status=\'accepted\' ORDER BY u.username',[req.user.id]);res.json(r.rows)});
app.get('/api/friends/pending',auth,async(req,res)=>{const r=await pool.query('SELECT f.id,f.requester_id,u.username FROM friendships f JOIN users u ON u.id=f.requester_id WHERE f.receiver_id=$1 AND f.status=\'pending\' ORDER BY f.created_at DESC',[req.user.id]);res.json(r.rows)});
app.post('/api/friends/:id/accept',auth,async(req,res)=>{const r=await pool.query('UPDATE friendships SET status=\'accepted\' WHERE id=$1 AND receiver_id=$2 AND status=\'pending\' RETURNING requester_id',[Number(req.params.id),req.user.id]);if(!r.rowCount)return res.status(404).json({error:'Demande introuvable'});await pool.query('INSERT INTO notifications(user_id,type,title,body) VALUES($1,\'friend_accept\',\'Demande acceptée\',$2)',[r.rows[0].requester_id,'Vous êtes maintenant amis.']);res.json({ok:true})});
app.post('/api/friends/:id/reject',auth,async(req,res)=>{await pool.query('DELETE FROM friendships WHERE id=$1 AND receiver_id=$2 AND status=\'pending\'',[Number(req.params.id),req.user.id]);res.json({ok:true})});
app.post('/api/blocks',auth,async(req,res)=>{const id=Number(req.body.userId);if(!id||id===req.user.id)return res.status(400).json({error:'Utilisateur invalide'});await pool.query('INSERT INTO blocks(blocker_id,blocked_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.user.id,id]);await pool.query('DELETE FROM friendships WHERE (requester_id=$1 AND receiver_id=$2) OR (requester_id=$2 AND receiver_id=$1)',[req.user.id,id]);res.json({ok:true})});
app.post('/api/reports',auth,async(req,res)=>{const id=Number(req.body.userId),reason=(req.body.reason||'Autre').slice(0,80),details=(req.body.details||'').slice(0,2000);if(!id)return res.status(400).json({error:'Utilisateur invalide'});await pool.query('INSERT INTO reports(reporter_id,reported_user_id,reason,details) VALUES($1,$2,$3,$4)',[req.user.id,id,reason,details]);res.status(201).json({ok:true})});
app.get('/api/notifications',auth,async(req,res)=>{const r=await pool.query('SELECT * FROM notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT 30',[req.user.id]);res.json(r.rows)});
app.post('/api/notifications/read',auth,async(req,res)=>{await pool.query('UPDATE notifications SET read_at=NOW() WHERE user_id=$1 AND read_at IS NULL',[req.user.id]);res.json({ok:true})});
app.post('/api/conversations/direct',auth,async(req,res)=>{const other=Number(req.body.userId);const b=await pool.query('SELECT 1 FROM blocks WHERE (blocker_id=$1 AND blocked_id=$2) OR (blocker_id=$2 AND blocked_id=$1)',[req.user.id,other]);if(b.rowCount)return res.status(403).json({error:'Conversation bloquée'});const f=await pool.query('SELECT 1 FROM friendships WHERE status=\'accepted\' AND ((requester_id=$1 AND receiver_id=$2) OR (requester_id=$2 AND receiver_id=$1))',[req.user.id,other]);if(!f.rowCount)return res.status(403).json({error:'Vous devez être amis'});const old=await pool.query('SELECT c.id FROM conversations c JOIN conversation_members a ON a.conversation_id=c.id AND a.user_id=$1 JOIN conversation_members b ON b.conversation_id=c.id AND b.user_id=$2 LIMIT 1',[req.user.id,other]);if(old.rowCount)return res.json({conversationId:old.rows[0].id});const c=await pool.connect();try{await c.query('BEGIN');const q=await c.query('INSERT INTO conversations DEFAULT VALUES RETURNING id'),id=q.rows[0].id;await c.query('INSERT INTO conversation_members VALUES($1,$2),($1,$3)',[id,req.user.id,other]);await c.query('COMMIT');res.status(201).json({conversationId:id})}catch{await c.query('ROLLBACK');res.status(500).json({error:'Conversation impossible'})}finally{c.release()}});
app.get('/api/conversations/:id/messages',auth,async(req,res)=>{const id=Number(req.params.id),m=await pool.query('SELECT 1 FROM conversation_members WHERE conversation_id=$1 AND user_id=$2',[id,req.user.id]);if(!m.rowCount)return res.status(403).json({error:'Accès refusé'});const r=await pool.query('SELECT m.id,m.sender_id,u.username,m.content,m.created_at FROM messages m JOIN users u ON u.id=m.sender_id WHERE m.conversation_id=$1 ORDER BY m.id',[id]);res.json(r.rows)});
app.post('/api/conversations/:id/messages',auth,async(req,res)=>{const id=Number(req.params.id),content=(req.body.content||'').trim();const m=await pool.query('SELECT 1 FROM conversation_members WHERE conversation_id=$1 AND user_id=$2',[id,req.user.id]);if(!m.rowCount)return res.status(403).json({error:'Accès refusé'});if(!content||content.length>2000)return res.status(400).json({error:'Message invalide'});const r=await pool.query('INSERT INTO messages(conversation_id,sender_id,content) VALUES($1,$2,$3) RETURNING *',[id,req.user.id,content]);res.status(201).json(r.rows[0])});
app.post('/api/ai/correct',auth,async(req,res)=>{const text=(req.body.text||'').trim();if(!text)return res.status(400).json({error:'Texte manquant'});if(process.env.OPENAI_API_KEY){try{const OpenAI=require('openai');const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const r=await client.responses.create({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',input:`Tu es le tuteur de SPEAK NOW. Corrige cette phrase sans être sévère. Donne: correction, explication courte. Phrase: ${text}`});return res.json({answer:r.output_text})}catch(e){console.error(e)}}res.json({answer:'Mode local : vérifie le temps du verbe, l’ordre des mots et les articles. Ajoute une clé OPENAI_API_KEY pour activer la correction IA réelle.'})});
init().then(()=>app.listen(process.env.PORT||3000,()=>console.log('SPEAK NOW v2.1 API démarrée'))).catch(console.error);
